export const QUERY_KEY = {
  GET_ME: "get_me",
  GET_ACCESS_TOKEN: "get_access_token",
  GET_ALL_USERS: "get_all_users",
  GET_USER_BY_ID: "get_user_by_id",
  MEDICINES: "medicines",
  BATCHES: "batches",
  VENDORS: "vendors",
  CUSTOMERS: "customers",
  PURCHASES: "purchases",
  SALES: "sales",
  STOCK_ADJUSTMENTS: "stock-adjustments",
  DASHBOARD_STATS: "dashboard-stats",
  LOW_STOCK: "low-stock",
  SALES_TREND: "sales-trend",
  SHOP_SETTINGS: "shop-settings",
  USERS: "users",
  ROLES: "roles",
  REPORTS: "reports",
  SEARCH: "search",
};
